<?xml version="1.0"?>
<robot name="mr_base_macro" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!--<xacro:include filename="$(find kvaradrive)/urdf/utility_macro.xacro" />-->
  <xacro:include filename="$(find kvaradrive)/urdf/utility_macro.xacro" />
  

  <!-- Base properties -->
	<xacro:property name="base_height" value="0.180" /> 
  <xacro:property name="base_radius" value="0.11" /> 
  <xacro:property name="base_mass" value="5" />
  <xacro:property name="wheel_mass" value="2.5" />
  <xacro:property name="wheel_radius" value="0.035" /> 
  <xacro:property name="wheel_axle" value="0.130" /> 

  <!-- WHOLE BASE MACRO-->
  <xacro:macro name="mr_base" > <!--fb : front, back ; lr: left, right -->
   
    
    <!--Actual body/chassis of the robot-->
    <link name="base_footprint">
    </link>

    <link name="base_link">
      <inertial>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        <mass value="${base_mass}" />
        <origin xyz="0 0 0" />
        <cylinder_inertia  m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>    
      <visual> 
        <geometry>
          <mesh filename="package://kvaradrive/meshes/mr_body.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="White"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0.0 ${(base_height/2.0)-0.05}"/>
      </collision> 
      <collision>
        <geometry>
          <sphere radius="0.019"/>
        </geometry>
        <origin rpy="0 0 0" xyz="-0.0825 0.0 -0.04"/>
      </collision>       
    </link>

    <link name="left_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="package://kvaradrive/meshes/mr_wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="Black"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
      <collision> 
        <geometry>
          <mesh filename="package://kvaradrive/meshes/mr_wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001" />
      </inertial>
    </link>

    <link name="right_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="package://kvaradrive/meshes/mr_wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="Black"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
      <collision> 
        <geometry>
          <mesh filename="package://kvaradrive/meshes/mr_wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001" />
      </inertial>
    </link>

   
    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.059"/>
    </joint>
    
    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_wheel_link"/>
      <origin rpy="0 0 0" xyz="0.04025 0.062 -0.024"/>
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.5" friction="0.01"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
      <origin rpy="0 0 ${-M_PI}" xyz="0.04025 -0.062 -0.024"/>
      <axis xyz="0 -1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.5" friction="0.01"/>
    </joint>

    <transmission name="left_wheel_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint">
	<hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="left_wheel_motor">
	<hardwareInterface>EffortJointInterface</hardwareInterface>
	<mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="right_wheel_tran">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint">
	<hardwareInterface>EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="right_wheel_motor">
	<hardwareInterface>EffortJointInterface</hardwareInterface>
	<mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    
    <!--Lidar sensor -->
 <link name="laser">
      <inertial>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        <mass value="0.1" />
        <origin xyz="0 0 0" />
        <cylinder_inertia  m="0.1" r="0.037" h="0.04" />
      </inertial>    
      <visual> 
        <geometry>
          <mesh filename="package://kvaradrive/meshes/lidar.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="White"/>
        <origin rpy="0 0 ${-M_PI_2}" xyz="0.0 0.0 -0.031"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry>
          <cylinder length="0.04" radius="0.037" />
        </geometry>
        <origin rpy="0 0 0" xyz="0.0 0.0 -0.031"/>
      </collision> 
         
    </link>

    <joint name="laser_joint" type="fixed">
      <parent link="base_link"/>
      <child link="laser"/>
      <origin rpy="0 0 0" xyz="0.0 0.0 0.155"/>
    </joint>

    <gazebo reference="laser">
      <sensor type="ray" name="head_hokuyo_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>40</update_rate>
        <ray>
            <scan>
              <horizontal>
                <samples>720</samples>
                <resolution>1</resolution>
                <min_angle>-${M_PI} </min_angle>
                <max_angle>${M_PI} </max_angle>
              </horizontal>
            </scan>
            <range>
              <min>0.8</min>
              <max>30.0</max>
              <resolution>0.01</resolution>
            </range>
            <noise>
              <type>gaussian</type>
              <!-- Noise parameters based on published spec for Hokuyo laser
                    achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                    stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                    reading. -->
              <mean>0.0</mean>
              <stddev>0.01</stddev>
            </noise>
        </ray>
        <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
            <topicName>/laser/scan</topicName>
            <frameName>laser</frameName>
        </plugin>
      </sensor>
    </gazebo>
    
    <!--Camera sensor -->
 <link name="camera_link">
      <inertial>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        <mass value="0.1" />
        <origin xyz="0 0 0" />
      </inertial>    
      <visual> 
        <geometry>
		<cylinder length="0.01" radius="0.005"/>
        </geometry>
        <material name="White"/>
        <origin rpy="0 ${-M_PI_2} 0" xyz="0 0 0"/>
      </visual>
      <collision>
        <geometry>
		<cylinder length="0.01" radius="0.005"/>
        </geometry>
        <origin rpy="0 ${-M_PI_2} 0" xyz="0 0 0"/>
      </collision> 
         
    </link>

    <joint name="camera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="camera_link"/>
      <origin rpy="${M_PI} 0 0" xyz="0.11 0.0 -0.01"/>
      <!-- <origin rpy="0 0 0" xyz="0.12 0.0 -0.01"/>  -->
    </joint>    
    
    <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>600</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>/camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

    <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>true</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo> 


     <gazebo reference="base_link">
      <material>Gazebo/White</material>
    </gazebo>

    <gazebo reference="left_wheel_link">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="1000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

     <gazebo reference="right_wheel_link">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="1000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

   </xacro:macro>
</robot>

